### ISSUE TITLE
format number

### ISSUE THREAD

**Issue by ghost** [matriphe/format#3]
how do i format

```
9762
```

to

```
9,762 ( Comma )
```

instead of

```
9.762 ( Dot )
```

because that's the way a Thousands should be formatted

![](https://universomates.files.wordpress.com/2008/11/place_value1.gif)

**Comment by matriphe** [comment]
just pass the parameter,
`Format::number((float) $number, (int) $precision = 0, (string) $decimal = ',', (string) $thousand = '.')`

Try this: `Format::number(9762, 0, '.', ',');`
