### ISSUE TITLE
Laravel upgrade to 5.4

### ISSUE THREAD

**Issue by ghost** [matriphe/format#5]
Can't upgrade Laravel to 5.4
Call to undefined method Illuminate\Foundation\Application::share()
As of laravel 5.4 share has been removed. You will have to use the singleton instead.

**Comment by matriphe** [comment]
thanks for the issue. I will check it.

**Comment by ghost** [comment]
possible to do so:
in file FormatServiceProvider
add
use Illuminate\Foundation\Application;
and
.....
public` function register()
{
	if (method_exists(Application::class, 'singleton')) { // for laravel 5.4
		$this->app->singleton('format', function ($app) {
			return new Format();
		});
	} else {
		$this->app['format'] = $this->app->share(function ($app) {  // for laravel <=  5.3
			return new Format();
		});
	}
}
.....

**Comment by ghost** [comment]
thanks...
